---
title: mc-inside
baseurl: http://inside.mcfog.wang/
MetaDataFormat: yaml
theme: glimmervoid

Paginate: 20

permalinks:
  post: "/:year/:month/:filename/"

taxonomies:
  category: "categories"
  tag: "tags"

params:
  Description: ""
  Copyright: "©mcfog All rights reserved."
---