---
title: mc-inside
baseurl: http://inside.mcfog.wang/
MetaDataFormat: yaml

permalinks:
  post: "/:year/:month/:filename/"

taxonomies:
  category: "categories"

params:
  Description: ""
  Copyright: "©mcfog All rights reserved."
---